version: '4'

services:

  mqa-score:
    image: mqa-scoring:v1.0.0
    container_name: mqa-score
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      - PORT=8000

  db:
    container_name: mongodb
    image: mongo:4.4
    command: --nojournal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_PASSWORD=BeOpen2023!
    ports:
      - '127.0.0.1:27017:27017'
    volumes: 
      - ./data:/data/db